package SSU_WHS.General;

import java.util.List;

public class cPublicDefinitions {
    public static String SETTINGS_PASSWORD = "ics";
    public static String UPDATE_BASE_URL = "http://ssupdate.icsvertex.nl";
    public static String UPDATE_PACKAGE_NAME = "scansuite.apk";

    public static String INTERFACE_VERSION = "15002";

    public static String NUMBERINTENT_NUMBER = "NUMBERINTENT_NUMBER";
    public static String NUMBERINTENT_EXTRANUMBER = "NUMBERINTENT_EXTRANUMBER";

    public static String NUMBERINTENT_CURRENTQUANTITY = "NUMBERINTENT_CURRENTQUANTITY";
    public static String NUMBERINTENT_MINQUANTITY = "NUMBERINTENT_MINQUANTITY";
    public static String NUMBERINTENT_MAXQUANTITY = "NUMBERINTENT_MAXQUANTITY";

    public static String PICKING_CHOSENORDER = "PICKING_CHOSENORDER";
    public static String PICKING_CHOSENITEMNO = "PICKING_CHOSENITEMNO";
    public static String PICKING_CHOSENLOCATION = "PICKING_CHOSENLOCATION";
    public static String PICKING_SCANNEDBARCODE = "PICKING_SCANNEDBARCODE";

    public static String SORTING_CHOSENORDER = "PICKING_CHOSENORDER";
    public static String SORTING_SCANNEDBARCODE = "SORTING_SCANNEDBARCODE";
    public static String SORTING_CHOSENITEMNO = "PICKING_CHOSENITEMNO";
    public static String SORTING_CHOSENWORKPLACE = "SORTING_CHOSENWORKPLACE";

    public static String SHIPPING_CHOSENORDER = "SHIPPING_CHOSENORDER";
    public static String SHIPPING_SCANNEDBARCODE = "SHIPPING_SCANNEDBARCODE";
    public static String SHIPPING_CHOSENITEMNO = "SHIPPING_CHOSENITEMNO";
    public static String SHIPPING_CHOSENWORKPLACE = "SHIPPING_CHOSENWORKPLACE";
    public static String SHIPPING_CHOSENSOURCENO = "SHIPPING_CHOSENSOURCENO";

    public String GENERICITEMEXTRAFIELD1;
    public String GENERICITEMEXTRAFIELD2;
    public String GENERICITEMEXTRAFIELD3;
    public String GENERICITEMEXTRAFIELD4;

    public static String SHIPPINGUNITFRAGMENT_SHIPPINGAGENT = "SHIPPINGUNITFRAGMENT_SHIPPINGAGENT";
    public static String SHIPPINGUNITFRAGMENT_SHIPPINGSERVICE = "SHIPPINGUNITFRAGMENT_SHIPPINGSERVICE";

    public static int CHANGELANGUAGE_REQUESTCODE = 45;
    public static int CHANGEDATETIME_REQUESTCODE = 46;
    public static int CHANGEWIFI_REQUESTCODE = 47;

    public static String TIMEPATTERNSHOW = "hh:mm";
    public static String DATEPATTERNSHOW = "dd-MM-yyyy";
    //public static String DATEPATTERNWEBSERVICE = "yyyy/MM/dd HH:mm:ss";
    public static String DATEPATTERNWEBSERVICE = "yyyy-MM-dd'T'hh:mm:ss'Z'";


    public static String SHAREDPREFERENCE_FILE = "SCANSUITE_PREFERENCES";
    public static String PREFERENCE_CURRENT_USER = "PREFERENCE_CURRENT_USER";
    public static String PREFERENCE_CURRENT_BRANCH = "PREFERENCE_CURRENT_BRANCH";
    public static String PREFERENCE_CURRENT_ORDER = "PREFERENCE_CURRENT_ORDER";
    public static String PREFERENCE_CURRENT_ENVIRONMENT = "PREFERENCE_CURRENT_ENVIRONMENT";

    public static String BARCODEFRAGMENT_LIST_TAG = "BARCODEFRAGMENT_LIST_TAG";
    public static String BRANCHFRAGMENT_LIST_TAG = "BRANCHFRAGMENT_LIST_TAG";

    public static String GETTING_DATA_TAG = "GETTING_DATA_TAG";

    public static String HUGEERROR_TAG = "HUGEERROR_TAG";
    public static String HUGEERROR_ERRORMESSAGE = "HUGEERROR_ERRORMESSAGE";
    public static String HUGEERROR_EXTRASTRING = "HUGEERROR_EXTRASTRING";

    public static String ORDERDONE_TAG = "ORDERDONE_TAG";
    public static String ORDERDONE_HEADER = "ORDERDONE_ERRORMESSAGE";
    public static String ORDERDONE_TEXT = "ORDERDONE_EXTRASTRING";
    public static String ORDERDONE_SHOWCURRENTLOCATION = "ORDERDONE_SHOWCURRENTLOCATION";

    public static String WEBSERVICEERROR_TAG = "WEBSERVICEERROR_TAG";
    public static String WEBSERVICEERROR_LIST_TAG = "WEBSERVICEERROR_LIST_TAG";

    public static String CURRENTLOCATION_TAG = "ORDERDONE_TAG";
    public static String CURRENTLOCATION_HEADER = "CURRENTLOCATION_HEADER";
    public static String CURRENTLOCATION_TEXT = "CURRENTLOCATION_TEXT";


    public static String ARTICLEFULL_TAG = "ARTICLEFULL_TAG";
    public static String ARTICLEFULL_RECORDID = "ARTICLEFULL_RECORDID";

    public static String SHOWCOMMENTS_EXTRA = "SHOWCOMMENTS_EXTRA";

    public static String CURRENT_ACTIVITY = "";

}
