package ICS.Utils.Scanning.gs1utils;

public class cGS1Definitions {

    public static ApplicationIdentifier getApplicationIdentifier(int identCode) {
        switch (identCode) {
            case 00:
                return ApplicationIdentifier.SSCC;
            case 01:
                return ApplicationIdentifier.GTIN;
            case 10:
                return ApplicationIdentifier.BATCH_OR_LOT_NUMBER;
            case 11:
                return ApplicationIdentifier.PRODUCTION_DATE;
            case 12:
                return ApplicationIdentifier.DUE_DATE;
            case 13:
                return ApplicationIdentifier.PACKAGING_DATE;
            case 15:
                return ApplicationIdentifier.BEST_BEFORE_DATE;
            case 16:
                return ApplicationIdentifier.SELL_BY_DATE;
            case 17:
                return ApplicationIdentifier.EXPIRATION_DATE;
            case 20:
            return ApplicationIdentifier.VARIANT_NUMBER;
                    case 21:
            return ApplicationIdentifier.SERIAL_NUMBER;
                    case 240:
            return ApplicationIdentifier.ADDITIONAL_ITEM_ID;
                    case 241:
            return ApplicationIdentifier.CUSTOMER_PART_NUMBER;
                    case 242:
            return ApplicationIdentifier.MADE_TO_ORDER_VARIATION_NUMBER;
                    case 243:
            return ApplicationIdentifier.PACKAGING_COMPONENT_NUMBER;
                    case 250:
            return ApplicationIdentifier.SECONDARY_SERIAL_NUMBER;
                    case 251:
            return ApplicationIdentifier.REFERENCE_TO_SOURCE_ENTITY;
                    case 253:
            return ApplicationIdentifier.GDTI;
                    case 254:
            return ApplicationIdentifier.GLN_EXTENSION_COMPONENT;
                    case 255:
            return ApplicationIdentifier.GCN;
                    case 30:
            return ApplicationIdentifier.VARIABLE_COUNT;
                    case 310:
            return ApplicationIdentifier.ITEM_NET_WEIGHT_KG;
                    case 311:
            return ApplicationIdentifier.ITEM_LENGTH_METRES;
                    case 312:
            return ApplicationIdentifier.ITEM_WIDTH_METRES;
                    case 313:
            return ApplicationIdentifier.ITEM_HEIGHT_METRES;
                    case 314:
            return ApplicationIdentifier.ITEM_AREA_SQUARE_METRES;
                    case 315:
            return ApplicationIdentifier.ITEM_NET_VOLUME_LITRES;
                    case 316:
            return ApplicationIdentifier.ITEM_NET_VOLUME_CUBIC_METRES;
                    case 320:
            return ApplicationIdentifier.ITEM_NET_WEIGHT_POUNDS;
                    case 321:
            return ApplicationIdentifier.ITEM_LENGTH_INCHES;
                    case 322:
            return ApplicationIdentifier.ITEM_LENGTH_FEET;
                    case 323:
            return ApplicationIdentifier.ITEM_LENGTH_YARDS;
                    case 324:
            return ApplicationIdentifier.ITEM_WIDTH_INCHES;
                    case 325:
            return ApplicationIdentifier.ITEM_WIDTH_FEET;
                    case 326:
            return ApplicationIdentifier.ITEM_WIDTH_YARDS;
                    case 327:
            return ApplicationIdentifier.ITEM_HEIGHT_INCHES;
                    case 328:
            return ApplicationIdentifier.ITEM_HEIGHT_FEET;
                    case 329:
            return ApplicationIdentifier.ITEM_HEIGHT_YARDS;
                    case 330:
            return ApplicationIdentifier.CONTAINER_GROSS_WEIGHT_KG;
                    case 331:
            return ApplicationIdentifier.CONTAINER_LENGTH_METRES;
                    case 332:
            return ApplicationIdentifier.CONTAINER_WIDTH_METRES;
                    case 333:
            return ApplicationIdentifier.CONTAINER_HEIGHT_METRES;
                    case 334:
            return ApplicationIdentifier.CONTAINER_AREA_SQUARE_METRES;
                    case 335:
            return ApplicationIdentifier.CONTAINER_VOLUME_LITRES;
                    case 336:
            return ApplicationIdentifier.CONTAINER_VOLUME_CUBIC_METRES;
                    case 337:
            return ApplicationIdentifier.KILOGRAMS_PER_SQUARE_METRE;
                    case 340:
            return ApplicationIdentifier.CONTAINER_GROSS_WEIGHT_POUNDS;
                    case 341:
            return ApplicationIdentifier.CONTAINER_LENGTH_INCHES;
                    case 342:
            return ApplicationIdentifier.CONTAINER_LENGTH_FEET;
                    case 343:
            return ApplicationIdentifier.CONTAINER_LENGTH_YARDS;
                    case 344:
            return ApplicationIdentifier.CONTAINER_WIDTH_INCHES;
                    case 345:
            return ApplicationIdentifier.CONTAINER_WIDTH_FEET;
                    case 346:
            return ApplicationIdentifier.CONTAINER_WIDTH_YARDS;
                    case 347:
            return ApplicationIdentifier.CONTAINER_HEIGHT_INCHES;
                    case 348:
            return ApplicationIdentifier.CONTAINER_HEIGHT_FEET;
                    case 349:
            return ApplicationIdentifier.CONTAINER_HEIGHT_YARDS;
                    case 350:
            return ApplicationIdentifier.ITEM_AREA_SQUARE_INCHES;
                    case 351:
            return ApplicationIdentifier.ITEM_AREA_SQUARE_FEET;
                    case 352:
            return ApplicationIdentifier.ITEM_AREA_SQUARE_YARDS;
                    case 353:
            return ApplicationIdentifier.CONTAINER_AREA_SQUARE_INCHES;
                    case 354:
            return ApplicationIdentifier.CONTAINER_AREA_SQUARE_FEET;
                    case 355:
            return ApplicationIdentifier.CONTAINER_AREA_SQUARE_YARDS;
                    case 356:
            return ApplicationIdentifier.ITEM_NET_WEIGHT_TROY_OUNCES;
                    case 357:
            return ApplicationIdentifier.ITEM_NET_VOLUME_OUNCES;
                    case 360:
            return ApplicationIdentifier.ITEM_NET_VOLUME_QUARTS;
                    case 361:
            return ApplicationIdentifier.ITEM_NET_VOLUME_GALLONS;
                    case 362:
            return ApplicationIdentifier.CONTAINER_VOLUME_QUARTS;
                    case 363:
            return ApplicationIdentifier.CONTAINER_VOLUME_GALLONS;
                    case 364:
            return ApplicationIdentifier.ITEM_NET_VOLUME_CUBIC_INCHES;
                    case 365:
            return ApplicationIdentifier.ITEM_NET_VOLUME_CUBIC_FEET;
                    case 366:
            return ApplicationIdentifier.ITEM_NET_VOLUME_CUBIC_YARDS;
                    case 367:
            return ApplicationIdentifier.CONTAINER_VOLUME_CUBIC_INCHES;
                    case 368:
            return ApplicationIdentifier.CONTAINER_VOLUME_CUBIC_FEET;
                    case 369:
            return ApplicationIdentifier.CONTAINER_VOLUME_CUBIC_YARDS;
                    case 37:
            return ApplicationIdentifier.COUNT_OF_TRADE_ITEMS;
                    case 390:
            return ApplicationIdentifier.AMOUNT_PAYABLE;
                    case 391:
            return ApplicationIdentifier.AMOUNT_PAYABLE_WITH_CURRENCY;
                    case 392:
            return ApplicationIdentifier.AMOUNT_PAYABLE_PER_SINGLE_ITEM;
                    case 393:
            return ApplicationIdentifier.AMOUNT_PAYABLE_PER_SINGLE_ITEM_WITH_CURRENCY;
                    case 400:
            return ApplicationIdentifier.CUSTOMER_PURCHASE_ORDER_NUMBER;
                    case 401:
            return ApplicationIdentifier.CONSIGNMENT_NUMBER;
                    case 402:
            return ApplicationIdentifier.SHIPMENT_NUMBER;
                    case 403:
            return ApplicationIdentifier.ROUTING_CODE;
                    case 410:
            return ApplicationIdentifier.SHIP_TO_LOCATION;
                    case 411:
            return ApplicationIdentifier.BILL_TO_LOCATION;
                    case 412:
            return ApplicationIdentifier.PURCHASED_FROM_LOCATION;
                    case 413:
            return ApplicationIdentifier.SHIP_FOR_LOCATION;
                    case 414:
            return ApplicationIdentifier.PHYSICAL_LOCATION;
                    case 415:
            return ApplicationIdentifier.INVOICING_PARTY;
                    case 420:
            return ApplicationIdentifier.SHIP_TO_POSTAL_CODE;
                    case 421:
            return ApplicationIdentifier.SHIP_TO_POSTAL_CODE_WITH_COUNTRY;
                    case 422:
            return ApplicationIdentifier.COUNTRY_OF_ORIGIN;
                    case 423:
            return ApplicationIdentifier.COUNTRY_OF_INITIAL_PROCESSING;
                    case 424:
            return ApplicationIdentifier.COUNTRY_OF_PROCESSING;
                    case 425:
            return ApplicationIdentifier.COUNTRY_OF_DISASSEMBLY;
                    case 426:
            return ApplicationIdentifier.COUNTRY_OF_FULL_PROCESS_CHAIN;
                    case 427:
            return ApplicationIdentifier.COUNTRY_SUBDIVISION_OF_ORIGIN;
                    case 7001:
            return ApplicationIdentifier.NATO_STOCK_NUMBER;
                    case 7002:
            return ApplicationIdentifier.MEAT_CUT;
                    case 7003:
            return ApplicationIdentifier.EXPIRATION_DATE_AND_TIME;
                    case 7004:
            return ApplicationIdentifier.ACTIVE_POTENCY;
                    case 7005:
            return ApplicationIdentifier.CATCH_AREA;
                    case 7006:
            return ApplicationIdentifier.FIRST_FREEZE_DATE;
                    case 7007:
            return ApplicationIdentifier.HARVEST_DATE;
                    case 7008:
            return ApplicationIdentifier.AQUATIC_SPECIES;
                    case 7009:
            return ApplicationIdentifier.FISHING_GEAR_TYPE;
                    case 7010:
            return ApplicationIdentifier.PRODUCTION_METHOD;
                    case 8001:
            return ApplicationIdentifier.ROLL_PRODUCT_DIMENSIONS;
                    case 8002:
            return ApplicationIdentifier.MOBILE_PHONE_IDENTIFIER;
                    case 8003:
            return ApplicationIdentifier.GRAI;
                    case 8004:
            return ApplicationIdentifier.GIAI;
                    case 8005:
            return ApplicationIdentifier.PRICE_PER_UNIT;
                    case 8006:
            return ApplicationIdentifier.GCTIN;
                    case 8007:
            return ApplicationIdentifier.IBAN;
                    case 8008:
            return ApplicationIdentifier.PRODUCTION_DATE_AND_TIME;
                    case 8010:
            return ApplicationIdentifier.COMPONENT_OR_PART_IDENTIFIER;
                    case 8011:
            return ApplicationIdentifier.COMPONENT_OR_PART_IDENTIFIER_SERIAL_NUMBER;
                    case 8012:
            return ApplicationIdentifier.SOFTWARE_VERSION;
                    case 8017:
            return ApplicationIdentifier.GSRN_PROVIDER;
                    case 8018:
            return ApplicationIdentifier.GSRN_RECIPIENT;
                    case 8019:
            return ApplicationIdentifier.SRIN;
                    case 8020:
            return ApplicationIdentifier.PAYMENT_SLIP_REFERENCE_NUMBER;
                    case 8110:
            return ApplicationIdentifier.COUPON_CODE_IDENTIFICATION_NORTH_AMERICA;
                    case 8111:
            return ApplicationIdentifier.COUPON_LOYALTY_POINTS;
                    case 8200:
            return ApplicationIdentifier.EXTENDED_PACKAGING_URL;
                    case 90:
            return ApplicationIdentifier.MUTUALLY_AGREED_INFORMATION;
                    case 91:
            return ApplicationIdentifier.COMPANY_INTERNAL_INFORMATION1;
                    case 92:
            return ApplicationIdentifier.COMPANY_INTERNAL_INFORMATION2;
                    case 93:
            return ApplicationIdentifier.COMPANY_INTERNAL_INFORMATION3;
                    case 94:
            return ApplicationIdentifier.COMPANY_INTERNAL_INFORMATION4;
                    case 95:
            return ApplicationIdentifier.COMPANY_INTERNAL_INFORMATION5;
                    case 96:
            return ApplicationIdentifier.COMPANY_INTERNAL_INFORMATION6;
                    case 97:
            return ApplicationIdentifier.COMPANY_INTERNAL_INFORMATION7;
                    case 98:
            return ApplicationIdentifier.COMPANY_INTERNAL_INFORMATION8;
                    case 99:
            return ApplicationIdentifier.COMPANY_INTERNAL_INFORMATION9;
                    default:
            return null;
        }
    }
}
